server:
  port: 8091 #应用服务端口
spring:
  application:
    name: dubbo-service1 #应用服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nacos服务地址
        namespace: 1f0a6510-d871-4875-af15-bd350075b3a7 #命名空间

#dubbo相关配置
dubbo:
  scan:
    base-packages: com.itheima.microservice #dubbo 扫描包路径
  registry:
    address: nacos://127.0.0.1:8848  #dubbo注册中心位置
  protocol:
    name: dubbo #dubbo协议
    port: 20881 #协议端口
  application:
    qos-enable: false #是否开启dubbo运维  不开启
  consumer:
    check: false #启动时就检查依赖的服务 关闭

